title: ReactFoo
subtitle: "India's community of React.js and React Native developers"
description: "India's community of React.js and React Native developers"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reactfoo.in" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .git
  - .sass_cache
  - _site
  - tests
  - vendor
  - .DS_Store
  - configs
  - deploy
  - requirements.txt
  - README.md

destination: _site/reactfoo

sass_dir: _sass

liquid:
  error_mode: strict

collections:
  reactfoo_events:
    type: event
    output: true
    permalink: /:path/
